name: Update Daily Market Data

# ✅ This grants permission to push code
permissions:
  contents: write

on:
  schedule:
    # Every 5 min between 03:45–10:05 UTC (i.e., 09:15–15:35 IST), Mon–Fri
    - cron: '*/5 3 * * 1-5'  # 03:00–03:59 UTC
    - cron: '*/5 4 * * 1-5'  # 04:00–04:59 UTC
    - cron: '*/5 5 * * 1-5'  # ...
    - cron: '*/5 6 * * 1-5'
    - cron: '*/5 7 * * 1-5'
    - cron: '*/5 8 * * 1-5'
    - cron: '*/5 9 * * 1-5'
    - cron: '*/5 10 * * 1-5'  # 10:00–10:05 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Daily_Data.py
        run: |
          python scripts/Daily_Data.py

      - name: Commit and Push stock_universe.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static/data/stock_universe.json
          git commit -m "🔁 Auto-updated stock_universe.json at $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')" || echo "No changes"
          git push
