name: Update Daily Market Data

# ✅ This grants permission to push code
permissions:
  contents: write

on:
  schedule:
    - cron: '30 10 * * *'  # 4 PM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Daily_Data.py
        run: |
          python scripts/Daily_Data.py

      - name: Commit and Push Final_Data.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static/data/Final_Data.json
          git commit -m "🔁 Auto-update Final_Data.json (4 PM IST)" || echo "No changes"
          git push
